##############################
####### Endereco  #######
###############################

####### Criar um novo endereço #######
POST http://localhost:8080/enderecos HTTP/1.1
Content-Type: application/json

{
        "rua": "Joao Naves",
        "numero": "22",
        "cidade": "Uberlândia",
        "estado": "Minas Gerais",
        "cep": "23223232"

}

####### Criar um outro endereço #######
POST http://localhost:8080/enderecos HTTP/1.1
Content-Type: application/json

{
        "rua": "Av Rodon Pacheco",
        "numero": "222",
        "cidade": "Uberlandia",
        "estado": "Minas Gerais",
        "cep": "3333333"

}

#######  Listar todos os endereços #######
GET http://localhost:8080/enderecos HTTP/1.1


#######  Criar um novo pacote  #######
POST http://localhost:8080/pacotes HTTP/1.1
Content-Type: application/json

{
        "id": "123456pacote2",
        "destinatário": "Matuzalem",
        "status": "pendente",
        "endereco": {
            "id": 2
        }

}

#######  Criar um novo pacote  #######
POST http://localhost:8080/pacotes HTTP/1.1
Content-Type: application/json

{
        "id": "pacote1",
        "destinatário": "Maria Alvez",
        "status": "pendente",
        "endereco": {
            "id": 1
        }

}

#######  Criar um novo pacote  #######
POST http://localhost:8080/pacotes HTTP/1.1
Content-Type: application/json

{
        "id": "pacote2",
        "destinatário": "Joazinho",
        "status": "em transito",
        "endereco": {
            "id": 2
        }

}
 
#######  Criar um novo pacote  #######
POST http://localhost:8080/pacotes HTTP/1.1
Content-Type: application/json

{
        "id": "pacote3",
        "destinatário": "Jose Slva",
        "status": "em transito",
        "endereco": {
            "id": 1
        }

}

#######  Criar um novo pacote  #######
POST http://localhost:8080/pacotes HTTP/1.1
Content-Type: application/json

{
        "id": "pacote4",
        "destinatário": "Mariazinha",
        "status": "entregue",
        "endereco": {
            "id": 1
        }

}

#######  Atualizar pacote id 2   #######
PUT http://localhost:8080/pacotes/2 HTTP/1.1
Content-Type: application/json

{
        "destinatário": "Mariazinha",
        "status": "em transito",
        "endereco": {
            "id": 1
        }

}

#######   Atualizar pacote id 1   #######
PUT http://localhost:8080/pacotes/1 HTTP/1.1
Content-Type: application/json

{
        "destinatário": "Maria Joaquina",
        "status": "em transito",
        "endereco": {
            "id": 2
        }

}


#######   Listar pacote de id 3  #######
GET http://localhost:8080/pacotes/3 HTTP/1.1

######### # Listar todos os pacotes   #######
GET http://localhost:8080/pacotes HTTP/1.1


#######  Deletar o pacote de id 4  #######
DELETE http://localhost:8080/pacotes/4 HTTP/1.1


##############################
####### Rastreamento  #######
###############################

####### Get all rastreamentos para o pacote de id 1  #######
GET http://localhost:8080/rastreamentos/1

####### Get all rastreamentos para o pacote de id 2  #######
GET http://localhost:8080/rastreamentos/1

###
### Pacote
###